$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: triton-multimodel
endpoint_name: {{endpt_name}}
model: azureml:triton-multimodel:1  
model_mount_path: /var
environment: 
  name: triton-image
  image: {{acr_name}}.azurecr.io/azureml-examples/triton-multimodel:1
  inference_config:
    liveness_route:
        path: /v2/health/live
        port: 8000
    readiness_route:
        path: /v2/health/ready
        port: 8000
    scoring_route:
        path: /
        port: 8000
instance_type: Standard_DS4_v2 
instance_count: 1